name : Process File On Customer Input

on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
    - uses: actions/checkout@v3

    - name: Authenticate to GCP
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SA_KEY }}
    
    - name: Setup cloud sdk
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id : ${{ secrets.PROJECT_ID }}
    
    - name: Upload Spark Job to GCS
      run : |
        gsutil cp spark-code-orders.py gs://..
    
    - name : Upload Airflow code to Dag
      run : |
        gcloud composer environments storage dags import \
        -- environment \
        -- location \
        --source airflow_dag_custom_input.py
